# Generated by Django 5.1.7 on 2025-03-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itbalgarche', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'ordering': ['-created_at'], 'verbose_name': 'About Me', 'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-created_at'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
    ]
