# Generated by Django 5.1.7 on 2025-03-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbalgarche', '0002_alter_aboutme_options_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
