# Generated by Django 5.1.7 on 2025-03-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbalgarche', '0004_certificate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
