# Generated by Django 5.1.7 on 2025-03-29 07:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbalgarche', '0005_certificate_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('link_text', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Data',
                'verbose_name_plural': 'Contact Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='certificate',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
