# Generated by Django 5.1.7 on 2025-03-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbalgarche', '0006_contactdata_alter_certificate_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
