# Generated by Django 5.1.7 on 2025-03-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbalgarche', '0009_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
