# Generated by Django 5.1.7 on 2025-03-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbalgarche', '0012_contactform_email_contactform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
