# Generated by Django 5.1.7 on 2025-03-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbalgarche', '0013_contactformmessage_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
