# Generated by Django 5.1.7 on 2025-03-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbalgarche', '0015_contactformmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
