# Generated by Django 5.1.7 on 2025-03-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbalgarche', '0016_alter_achievement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='placement',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=10, null=True),
        ),
    ]
